# Site settings
name: Karen M. Aguilar
title: Karen M. Aguilar | Electrical Engineer
description: Research-driven engineer focused on developing smart sensing systems and intuitive user experiences
url: https://karenmaguilar.github.io/
baseurl: ''
email: aguilarkaren423@gmail.com
#cover: https://bchiang7.github.io/img/og.png
#logo: https://bchiang7.github.io/img/emojis/technologist.png
#resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:aguilarkaren423.chiang@gmail.com
  - title: github
    url: https://github.com/karenmaguilar
  - title: linkedin
    url: https://www.linkedin.com/in/karen-m-aguilar

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
